/*
 * trainingStrings.js — the platform-standard labels every training game
 * shares: pause/quit dialog, mode names, Pass n Play setup and handoff.
 * Games spread these FIRST into their own string tables, so any game can
 * still override a label locally:
 *
 *   en: { ...STR_COMMON.en, myGameKey: '...' },
 *   ar: { ...STR_COMMON.ar, myGameKey: '...' },
 *
 * Keep wording changes here — they apply to all games at once.
 */
export const STR_COMMON = {
  en: {
    addPl: '＋ Add player',
    chalBulletPass: 'Tap Start only when the device is with this player',
    chalPickDiff: 'Difficulty',
    chalResTitle: 'Pass n Play results',
    chalRounds: 'Rounds',
    chalTurnKicker: 'Your turn',
    challengeHeader: 'Pass n Play',
    challengeMode: 'Pass n Play',
    challengeTitle: 'Pass n Play',
    freeGameOver: 'Run ended',
    freeHeader: 'Survival mode',
    freeIntroReady: 'Ready',
    freeIntroTitle: 'Survival mode',
    freeMode: 'Survival mode',
    freePlayAgain: 'Play again',
    goReady: 'Start',
    handTo: (n) => `Hand the device to ${n}.`,
    hubMapAria: 'Modes',
    hubTag: 'training',
    keep: 'Keep playing',
    levelCleared: 'Level cleared! ✓',
    levelMode: 'Level mode',
    levels: 'Levels',
    lives: 'Lives',
    menu: 'Menu',
    notQuite: 'Not quite',
    needTwo: 'Add at least 2 players.',
    newCh: 'New game',
    nextLv: 'Next level',
    passInstruction: 'Pass the device to this player, then tap Start',
    paused: 'Paused',
    pickDiff: 'Choose difficulty',
    readyName: (n) => `Ready — ${n}`,
    players: 'Players (2–10)',
    quitLose: 'This run will be lost.',
    quitMenu: 'Quit to menu',
    quitQ: 'Quit?',
    // `replay` is for a level you CLEARED; `retry` is for one you did not.
    // ModeShell used to render both as 'إعادة' in Arabic, which made a win and a
    // loss offer the identically-worded button.
    chalBulletSame: 'Same board for every player this round',
    replay: 'Replay',
    replayTutorial: 'Replay tutorial',
    resultsChalTitle: 'Pass n Play results',
    resume: 'Resume',
    retry: 'Retry',
    roundNofM: (n, m) => `Round ${n}/${m}`,
    score: 'Score',
    stars: 'Stars',
    startCh: '⚔️ Start',
    tag: 'training',
    time: 'Time',
    yesQuit: 'Yes, quit',
  },
  ar: {
    addPl: '＋ إضافة لاعب',
    chalBulletPass: 'اضغط ابدأ فقط عندما يكون الجهاز مع هذا اللاعب',
    chalPickDiff: 'الصعوبة',
    chalResTitle: 'نتائج مرّر والعب',
    chalRounds: 'الجولات',
    chalTurnKicker: 'دورك',
    challengeHeader: 'مرّر والعب',
    challengeMode: 'مرّر والعب',
    challengeTitle: 'مرّر والعب',
    freeGameOver: 'انتهت المحاولة',
    freeHeader: 'وضع البقاء',
    freeIntroReady: 'جاهز',
    freeIntroTitle: 'وضع البقاء',
    freeMode: 'وضع البقاء',
    freePlayAgain: 'العب مجددًا',
    goReady: 'ابدأ',
    handTo: (n) => `سلّم الجهاز إلى ${n}.`,
    hubMapAria: 'الأوضاع',
    hubTag: 'تدريب',
    keep: 'متابعة اللعب',
    levelCleared: 'أحسنت! ✓',
    levelMode: 'وضع المستويات',
    levels: 'المستويات',
    lives: 'الأرواح',
    menu: 'القائمة',
    notQuite: 'حاول مجدداً',
    needTwo: 'أضف لاعبين على الأقل.',
    newCh: 'لعبة جديدة',
    nextLv: 'المستوى التالي',
    passInstruction: 'سلّم الجهاز لهذا اللاعب ثم اضغط ابدأ',
    paused: 'متوقف',
    pickDiff: 'اختر الصعوبة',
    readyName: (n) => `جاهز — ${n}`,
    players: 'اللاعبون (2–10)',
    quitLose: 'سيُلغى هذا السجل.',
    quitMenu: 'الخروج للقائمة',
    quitQ: 'خروج؟',
    chalBulletSame: 'نفس اللوحة لكل اللاعبين هذه الجولة',
    replay: 'إعادة',
    replayTutorial: 'إعادة الشرح',
    resultsChalTitle: 'نتائج مرّر والعب',
    resume: 'متابعة',
    // Warmer than 'إعادة', and it no longer collides with `replay` above.
    retry: 'حاول مجدداً',
    roundNofM: (n, m) => `الجولة ${n}/${m}`,
    score: 'نقاط',
    stars: 'نجوم',
    startCh: '⚔️ ابدأ',
    tag: 'تدريب',
    time: 'الوقت',
    yesQuit: 'نعم، خروج',
  },
};
