/*
 * THE WHEEL — the second content batch.
 *
 * Split from data.js purely for size. Everything here obeys the same rules and
 * is checked by the same `npm run validate:wheel`: unique ids, no two puzzles
 * over the same card set, no adjacent pair inside 8% (or the absolute year
 * minimum), truths reachable on their own slider, anchors on the wheel.
 *
 * The figures are the ones a reasonably-informed person could estimate, and
 * each `fact` line carries the precision that the rounded answer drops. Where a
 * number is genuinely contested or drifts year to year, it is either stated as
 * a round approximation or left out — a quiz that is confidently wrong is worse
 * than a shorter quiz.
 */
import { P, N, pool } from './bankHelpers.js';

export const MORE_WHEEL = [
  P('land-share', 'What percentage of Earth’s surface is land?', 29, 12, 65, 3, 'Land is the other 29% of the surface.'),
  P('sahara-africa', 'What percentage of Africa is covered by the Sahara?', 31, 12, 65, 5, 'The Sahara covers roughly a third of the continent.'),
  P('russia-land', 'What percentage of the world’s land area is Russia?', 11, 2, 42, 3, 'Russia alone holds about 11% of all land.'),
  P('muscle-adult', 'What percentage of a lean adult body is skeletal muscle?', 40, 12, 65, 6, 'Skeletal muscle is roughly 40% of a lean adult’s mass.'),
  P('brain-water', 'What percentage of the human brain is water?', 75, 42, 90, 5, 'Brain tissue is roughly three-quarters water.'),
  P('earth-iron', 'What percentage of Earth’s mass is iron?', 32, 12, 65, 6, 'Iron is the most abundant element by mass, mostly locked in the core.'),
  P('milk-water', 'What percentage of cow’s milk is water?', 87, 42, 90, 4, 'Milk is mostly water, with fat, protein and sugar making up the rest.'),
  P('egg-water', 'What percentage of an egg white is water?', 90, 42, 90, 4, 'Egg white is about 90% water; most of the rest is protein.'),
  P('body-carbon', 'What percentage of the human body is carbon by mass?', 18, 5, 42, 4, 'Carbon is second only to oxygen by mass in the body.'),
  P('body-oxygen', 'What percentage of the human body is oxygen by mass?', 65, 25, 90, 5, 'Mostly bound up in water.'),
  P('crust-oxygen', 'What percentage of Earth’s crust is oxygen by mass?', 46, 12, 90, 5, 'Oxygen is the most abundant element in the crust.'),
  P('sun-hydrogen', 'What percentage of the Sun’s mass is hydrogen?', 73, 42, 90, 5, 'Roughly 73% hydrogen and 25% helium.'),
  P('sleep-rem', 'What percentage of adult sleep is REM sleep?', 22, 5, 42, 5, 'Roughly a fifth to a quarter of a night.'),
  P('colour-blind-men', 'What percentage of men have red–green colour blindness?', 8, 2, 25, 3, 'About one man in twelve — and far fewer women.'),
  P('earth-desert', 'What percentage of Earth’s land is desert?', 33, 12, 65, 5, 'About a third of all land is desert, hot or cold.'),
  P('food-waste', 'What percentage of the world’s food is wasted or lost?', 33, 12, 65, 6, 'Roughly a third of all food produced is never eaten.'),
  P('renewable-electric', 'What percentage of the world’s electricity comes from renewables?', 30, 12, 65, 6, 'Renewables now supply roughly 30% of global electricity.'),
  P('literacy', 'What percentage of adults worldwide can read and write?', 87, 42, 90, 4, 'Global adult literacy is close to 87%.'),
  P('electricity-access', 'What percentage of the world has access to electricity?', 91, 42, 90, 4, 'About 91% of people have an electricity connection.'),
  P('china-india', 'What percentage of humanity lives in China and India combined?', 35, 12, 65, 5, 'The two largest countries hold roughly a third of humanity between them.'),
  P('greenland-ice', 'What percentage of Greenland is covered by ice?', 80, 42, 90, 5, 'The ice sheet covers about four fifths of the island.'),
  P('nile-egypt', 'What percentage of Egypt’s people live along the Nile?', 95, 42, 90, 4, 'Almost everyone lives on a narrow strip of valley and delta.'),
  P('atmosphere-low', 'What percentage of the atmosphere’s mass sits below 10 km?', 75, 42, 90, 6, 'Most of the air is in the troposphere.'),
  P('bone-water', 'What percentage of living bone is water?', 25, 5, 65, 6, 'Bone is far from dry — about a quarter of it is water.'),
  P('universe-hydrogen', 'What percentage of ordinary matter in the universe is hydrogen?', 75, 42, 90, 5, 'Hydrogen is by far the most common ordinary matter.'),

  N('sun-earths-across', 'How many Earths would fit across the Sun’s diameter?', ' Earths', 10, 300, false, 109, 42, 230, 12, 'The Sun is about 109 Earth diameters across.'),
  N('light-second', 'How many THOUSAND kilometres does light travel in a second?', 'k km', 10, 900, false, 300, 90, 600, 30, 'Just under 300,000 km every second.'),
  N('bones-baby', 'How many bones is a newborn baby born with?', ' bones', 100, 600, false, 300, 150, 600, 30, 'Around 300, many of which fuse into the adult 206.'),
  N('breaths-day', 'How many THOUSAND breaths does an adult take in a day?', 'k', 1, 90, false, 22, 5, 65, 4, 'At about 15 a minute, roughly 22,000 a day.'),
  N('heart-litres', 'How many THOUSAND litres of blood does a heart pump in a day?', 'k L', 1, 30, false, 7, 2, 25, 2, 'About 7,000 litres every day.'),
  N('blink-day', 'How many THOUSAND times does a person blink in a day?', 'k', 1, 60, false, 15, 5, 42, 4, 'Roughly 15,000 blinks.'),
  N('hair-head', 'How many THOUSAND hairs are on a typical human head?', 'k', 10, 400, false, 100, 42, 230, 20, 'About 100,000 hairs.'),
  N('neurons', 'How many BILLION neurons are in the human brain?', 'B', 5, 300, false, 86, 42, 230, 12, 'Around 86 billion.'),
  N('dna-metres', 'Stretched out, how many metres of DNA are in one human cell?', ' m', 0, 10, true, 2, 2, 12, 0.5, 'About two metres, packed into a nucleus a few microns wide.'),
  N('shark-bones', 'How many bones does a shark have?', ' bones', 0, 20, false, 0, 2, 12, 0.6, 'None — a shark’s skeleton is cartilage.'),
  N('elephant-teeth', 'How many working molars does an adult elephant use at once?', ' teeth', 1, 20, false, 4, 2, 12, 1, 'Four, replaced six times over a lifetime.'),
  N('starfish-arms', 'How many arms does a typical starfish have?', ' arms', 1, 20, false, 5, 2, 12, 1, 'Five, though some species grow many more.'),
  N('cow-stomachs', 'How many stomach compartments does a cow have?', '', 1, 12, false, 4, 2, 12, 0.8, 'Rumen, reticulum, omasum and abomasum.'),
  N('insect-legs', 'How many legs does an insect have?', ' legs', 1, 20, false, 6, 2, 12, 1, 'Six — that is what makes it an insect.'),
  N('rainbow-colours', 'How many colours are traditionally counted in a rainbow?', ' colours', 1, 20, false, 7, 2, 12, 1, 'Newton settled on seven.'),
  N('sudoku-cells', 'How many cells are in a standard sudoku grid?', ' cells', 10, 300, false, 81, 42, 150, 5, 'Nine rows of nine.'),
  N('dominoes', 'How many tiles are in a double-six domino set?', ' tiles', 5, 90, false, 28, 12, 65, 3, '28 tiles, every pair of numbers from blank to six.'),
  N('scrabble-tiles', 'How many tiles are in an English Scrabble set?', ' tiles', 20, 300, false, 100, 42, 230, 8, '100 tiles, including two blanks.'),
  N('monopoly-squares', 'How many spaces are around a Monopoly board?', ' spaces', 10, 150, false, 40, 12, 90, 4, '40 spaces, including the four corners.'),
  N('rubik-stickers', 'How many coloured stickers are on a Rubik’s Cube?', ' stickers', 10, 200, false, 54, 25, 90, 4, 'Six faces of nine.'),
  N('bowling-pins', 'How many pins stand in a frame of ten-pin bowling?', ' pins', 1, 25, false, 10, 5, 25, 1, 'Ten, in a triangle.'),
  N('snooker-reds', 'How many red balls start a frame of snooker?', ' balls', 1, 42, false, 15, 5, 25, 2, 'Fifteen reds, plus six colours.'),
  N('rugby-team', 'How many players are on a rugby union team on the pitch?', ' players', 5, 30, false, 15, 5, 25, 2, 'Fifteen a side.'),
  N('basketball-team', 'How many players per team are on a basketball court?', ' players', 1, 20, false, 5, 2, 12, 1, 'Five a side, with unlimited substitutions.'),
  N('week-hours', 'How many hours are in one week?', ' h', 20, 400, false, 168, 90, 230, 10, '7 × 24 = 168.'),
  N('degrees-circle', 'How many degrees are in a full circle?', '°', 100, 800, false, 360, 230, 600, 15, '360 degrees, a division inherited from Babylonian astronomy.'),
  N('hexagon-angle', 'How many degrees is each interior angle of a regular hexagon?', '°', 30, 300, false, 120, 65, 230, 8, '720 degrees shared across six corners.'),
  N('primes-20', 'How many prime numbers are below 20?', ' primes', 1, 30, false, 8, 2, 25, 1, '2, 3, 5, 7, 11, 13, 17 and 19.'),
  N('pi', 'What is pi, to one decimal place?', '', 0, 10, true, 3.1, 2, 12, 0.4, 'π ≈ 3.14159…, and it never repeats or terminates.'),
  N('byte-bits', 'How many bits are in a byte?', ' bits', 1, 42, false, 8, 2, 25, 1, 'Eight bits, which is why a byte holds 256 values.'),
  N('continents', 'How many continents are usually counted?', '', 1, 20, false, 7, 2, 12, 1, 'Seven, in the most common convention.'),
  N('oceans-count', 'How many oceans are officially recognised?', ' oceans', 1, 20, false, 5, 2, 12, 1, 'Five, since the Southern Ocean was named.'),
  N('great-lakes', 'How many Great Lakes are there?', ' lakes', 1, 20, false, 5, 2, 12, 1, 'Superior, Michigan, Huron, Erie and Ontario.'),
  N('security-council', 'How many permanent members sit on the UN Security Council?', ' members', 1, 20, false, 5, 2, 12, 1, 'China, France, Russia, the UK and the USA.'),
  N('eu-members', 'How many member states are in the European Union?', ' states', 5, 90, false, 27, 12, 65, 3, '27 member states.'),
  N('arabic-letters', 'How many letters are in the Arabic alphabet?', ' letters', 5, 90, false, 28, 12, 65, 3, '28 letters, written from right to left.'),
  N('piano-white', 'How many WHITE keys are on a standard piano?', ' keys', 10, 150, false, 52, 25, 90, 4, '52 white and 36 black.'),
  N('guitar-strings', 'How many strings does a standard guitar have?', ' strings', 1, 20, false, 6, 2, 12, 1, 'Six strings, tuned E-A-D-G-B-E.'),
  N('violin-strings', 'How many strings does a violin have?', ' strings', 1, 12, false, 4, 2, 12, 0.8, 'G, D, A and E.'),
  N('zodiac', 'How many signs are in the Western zodiac?', ' signs', 1, 42, false, 12, 5, 25, 1, 'Twelve signs, one for each month-long solar arc.'),
  N('chess-pieces', 'How many pieces does each player start with in chess?', ' pieces', 5, 42, false, 16, 5, 25, 2, 'Eight pawns and eight others.'),
  N('potter-books', 'How many books are in the main Harry Potter series?', ' books', 1, 25, false, 7, 2, 12, 1, 'Seven books, published between 1997 and 2007.'),
  N('ancient-wonders', 'How many Wonders of the Ancient World were listed?', ' wonders', 1, 20, false, 7, 2, 12, 1, 'Seven — only the Great Pyramid survives.'),
  N('moonwalkers', 'How many people have walked on the Moon?', ' people', 1, 42, false, 12, 2, 25, 2, 'Twelve, all between 1969 and 1972.'),
  N('sun-age', 'How many BILLION years old is the Sun?', 'B yrs', 1, 20, true, 4.6, 2, 12, 1, 'About 4.6 billion years.'),
  N('universe-age', 'How many BILLION years old is the universe?', 'B yrs', 1, 42, true, 13.8, 5, 25, 1.5, 'About 13.8 billion years.'),
  N('dino-extinct', 'How many MILLION years ago did the non-avian dinosaurs die out?', 'M yrs', 5, 300, false, 66, 25, 150, 8, 'About 66 million years ago.'),
  N('ice-age-end', 'How many THOUSAND years ago did the last ice age end?', 'k yrs', 1, 90, false, 12, 2, 42, 3, 'Roughly 11,700 years ago.'),
  N('writing-invented', 'How many THOUSAND years ago was writing invented?', 'k yrs', 1, 42, false, 5, 2, 25, 1.5, 'Around 5,000 years ago, in Mesopotamia.'),
  N('titanic-year', 'In what year did the Titanic sink?', '', 1800, 2000, false, 1912, 1000, 600, 8, 'On its maiden voyage, April 1912.'),
  N('moon-landing', 'In what year did humans first walk on the Moon?', '', 1900, 2000, false, 1969, 1000, 600, 5, 'Apollo 11, July 1969.'),
  N('ww2-end', 'In what year did the Second World War end?', '', 1900, 2000, false, 1945, 1000, 600, 5, 'It ended in 1945.'),
  N('berlin-wall', 'In what year did the Berlin Wall fall?', '', 1900, 2000, false, 1989, 1000, 600, 5, 'November 1989.'),
];

export const MORE_STREAK = [
  { id: 'wingspans', title: 'WINGSPANS', titleAr: 'باع الأجنحة', unit: ' m', items: [['BEE HUMMINGBIRD', 0.07], ['SPARROW', 0.24], ['PIGEON', 0.65], ['SEAGULL', 1.4], ['GOLDEN EAGLE', 2.2], ['ALBATROSS', 3.4], ['CESSNA 172', 11], ['BOEING 737', 36], ['BOEING 747', 68], ['AIRBUS A380', 80]] },
  { id: 'eggs', title: 'EGG WEIGHTS', titleAr: 'أوزان البيض', unit: ' g', items: [['HUMMINGBIRD', 0.5], ['SPARROW', 3], ['PIGEON', 17], ['CHICKEN', 58], ['DUCK', 70], ['TURKEY', 85], ['GOOSE', 144], ['EMU', 560], ['OSTRICH', 1400]] },
  { id: 'citypop', title: 'CITY POPULATIONS', titleAr: 'سكان المدن', unit: ' M', items: [['REYKJAVIK', 0.14], ['BEIRUT', 2.4], ['ROME', 2.8], ['BERLIN', 3.8], ['LONDON', 9], ['CAIRO', 10], ['ISTANBUL', 15.8], ['DELHI', 33], ['TOKYO', 37]] },
  { id: 'islands', title: 'ISLAND AREAS', titleAr: 'مساحات الجزر', unit: ' k km²', items: [['MALTA', 0.3], ['BAHRAIN', 0.8], ['CYPRUS', 9.2], ['SICILY', 25], ['SRI LANKA', 65], ['IRELAND', 84], ['JAVA', 138], ['GREAT BRITAIN', 209], ['MADAGASCAR', 587], ['GREENLAND', 2166]] },
  { id: 'lakes', title: 'LAKE AREAS', titleAr: 'مساحات البحيرات', unit: ' k km²', items: [['LAKE GENEVA', 0.58], ['LAKE TAHOE', 0.5], ['LAKE ONTARIO', 19], ['LAKE ERIE', 25], ['LAKE MICHIGAN', 58], ['LAKE BAIKAL', 31], ['LAKE SUPERIOR', 82], ['LAKE VICTORIA', 69], ['CASPIAN SEA', 371]] },
  { id: 'buildingsyear', title: 'FINISHED IN', titleAr: 'اكتمل عام', unit: ' AD', gapAbs: 8, items: [['COLOSSEUM', 80], ['HAGIA SOPHIA', 537], ['NOTRE-DAME', 1345], ['ST PETER’S', 1626], ['TAJ MAHAL', 1653], ['EIFFEL TOWER', 1889], ['EMPIRE STATE', 1931], ['SYDNEY OPERA HOUSE', 1973], ['BURJ KHALIFA', 2010]] },
  { id: 'discoveries', title: 'DISCOVERED IN', titleAr: 'اكتُشف عام', unit: ' AD', gapAbs: 8, items: [['GRAVITY LAWS', 1687], ['OXYGEN', 1774], ['ELECTRON', 1897], ['PENICILLIN', 1928], ['DNA STRUCTURE', 1953], ['PLATE TECTONICS', 1965], ['BLACK HOLE IMAGE', 2019]] },
  { id: 'runspeed', title: 'HUMAN RECORDS', titleAr: 'أرقام قياسية', unit: ' sec', items: [['100 M', 9.58], ['200 M', 19.19], ['400 M', 43.03], ['800 M', 100.9], ['1500 M', 206], ['5000 M', 755], ['10000 M', 1571], ['MARATHON', 7235]] },
  { id: 'volcanoes', title: 'VOLCANO HEIGHTS', titleAr: 'ارتفاع البراكين', unit: ' m', items: [['STROMBOLI', 924], ['VESUVIUS', 1281], ['MOUNT ST HELENS', 2549], ['MOUNT ETNA', 3357], ['MOUNT FUJI', 3776], ['MOUNT RAINIER', 4392], ['KILIMANJARO', 5895], ['OJOS DEL SALADO', 6893]] },
  { id: 'bridges', title: 'BRIDGE SPANS', titleAr: 'أطوال الجسور', unit: ' m', items: [['PONTE VECCHIO', 95], ['TOWER BRIDGE', 244], ['BROOKLYN BRIDGE', 486], ['GOLDEN GATE', 1280], ['GREAT BELT', 1624], ['ÇANAKKALE 1915', 2023]] },
  { id: 'trees', title: 'TREE HEIGHTS', titleAr: 'ارتفاع الأشجار', unit: ' m', items: [['APPLE TREE', 4], ['OLIVE TREE', 9], ['BIRCH', 20], ['OAK', 30], ['NORWAY SPRUCE', 50], ['GIANT SEQUOIA', 84], ['COAST REDWOOD', 116]] },
  { id: 'seabeasts', title: 'SEA CREATURE LENGTHS', titleAr: 'أطوال كائنات البحر', unit: ' m', items: [['SEAHORSE', 0.15], ['CLOWNFISH', 0.11], ['OCTOPUS', 1], ['DOLPHIN', 2.5], ['GREAT WHITE SHARK', 4.6], ['ORCA', 8], ['GIANT SQUID', 13], ['WHALE SHARK', 12], ['BLUE WHALE', 30]] },
  { id: 'brainmass', title: 'BRAIN MASS', titleAr: 'كتلة الدماغ', unit: ' g', items: [['MOUSE', 0.4], ['SPARROW', 1], ['CAT', 30], ['DOG', 70], ['CHIMPANZEE', 400], ['HUMAN', 1350], ['DOLPHIN', 1600], ['ELEPHANT', 5000], ['SPERM WHALE', 7800]] },
  { id: 'coffee', title: 'CAFFEINE PER SERVING', titleAr: 'الكافيين لكل حصة', unit: ' mg', items: [['DECAF COFFEE', 3], ['GREEN TEA', 28], ['COLA', 34], ['BLACK TEA', 47], ['ESPRESSO SHOT', 63], ['ENERGY DRINK', 80], ['FILTER COFFEE', 95], ['LARGE BREWED COFFEE', 200]] },
  { id: 'moonsizes', title: 'MOON DIAMETERS', titleAr: 'أقطار الأقمار', unit: ' km', items: [['PHOBOS', 22], ['DEIMOS', 12], ['ENCELADUS', 504], ['MIMAS', 396], ['EUROPA', 3122], ['MOON', 3475], ['CALLISTO', 4821], ['GANYMEDE', 5268]] },
  { id: 'currencyage', title: 'COUNTRY FOUNDED', titleAr: 'تأسست عام', unit: ' AD', gapAbs: 8, items: [['SAN MARINO', 301], ['PORTUGAL', 1139], ['SWITZERLAND', 1291], ['USA', 1776], ['ITALY', 1861], ['AUSTRALIA', 1901], ['LEBANON', 1943], ['SOUTH SUDAN', 2011]] },
].map(pool);

export const MORE_RANKED = [
  { id: 'wingspan', prompt: 'SHORTEST → WIDEST WINGSPAN', promptAr: 'الأضيق ← الأوسع جناحاً', unit: ' m', items: [['SPARROW', 0.24], ['SEAGULL', 1.4], ['ALBATROSS', 3.4], ['CESSNA 172', 11], ['BOEING 747', 68]] },
  { id: 'egg', prompt: 'LIGHTEST → HEAVIEST EGG', promptAr: 'الأخف ← الأثقل بيضة', unit: ' g', items: [['HUMMINGBIRD', 0.5], ['SPARROW', 3], ['CHICKEN', 58], ['GOOSE', 144], ['OSTRICH', 1400]] },
  { id: 'city', prompt: 'SMALLEST → LARGEST CITY', promptAr: 'الأصغر ← الأكبر مدينة', unit: ' M people', items: [['REYKJAVIK', 0.14], ['BEIRUT', 2.4], ['LONDON', 9], ['ISTANBUL', 15.8], ['TOKYO', 37]] },
  { id: 'island', prompt: 'SMALLEST → LARGEST ISLAND', promptAr: 'الأصغر ← الأكبر جزيرة', unit: ' k km²', items: [['MALTA', 0.3], ['CYPRUS', 9.2], ['IRELAND', 84], ['MADAGASCAR', 587], ['GREENLAND', 2166]] },
  { id: 'volcano', prompt: 'LOWEST → HIGHEST VOLCANO', promptAr: 'الأدنى ← الأعلى بركاناً', unit: ' m', items: [['STROMBOLI', 924], ['VESUVIUS', 1281], ['MOUNT ETNA', 3357], ['MOUNT RAINIER', 4392], ['KILIMANJARO', 5895]] },
  { id: 'bridge', prompt: 'SHORTEST → LONGEST SPAN', promptAr: 'الأقصر ← الأطول امتداداً', unit: ' m', items: [['PONTE VECCHIO', 95], ['TOWER BRIDGE', 244], ['BROOKLYN BRIDGE', 486], ['GOLDEN GATE', 1280], ['ÇANAKKALE 1915', 2023]] },
  { id: 'tree', prompt: 'SHORTEST → TALLEST TREE', promptAr: 'الأقصر ← الأطول شجرة', unit: ' m', items: [['APPLE TREE', 4], ['BIRCH', 20], ['OAK', 30], ['GIANT SEQUOIA', 84], ['COAST REDWOOD', 116]] },
  { id: 'sea', prompt: 'SMALLEST → LARGEST SEA CREATURE', promptAr: 'الأصغر ← الأكبر بحرياً', unit: ' m', items: [['SEAHORSE', 0.15], ['DOLPHIN', 2.5], ['GREAT WHITE SHARK', 4.6], ['GIANT SQUID', 13], ['BLUE WHALE', 30]] },
  { id: 'brain', prompt: 'LIGHTEST → HEAVIEST BRAIN', promptAr: 'الأخف ← الأثقل دماغاً', unit: ' g', items: [['CAT', 30], ['CHIMPANZEE', 400], ['HUMAN', 1350], ['ELEPHANT', 5000], ['SPERM WHALE', 7800]] },
  { id: 'caffeine', prompt: 'LEAST → MOST CAFFEINE', promptAr: 'الأقل ← الأكثر كافيين', unit: ' mg', items: [['DECAF COFFEE', 3], ['GREEN TEA', 28], ['BLACK TEA', 47], ['ENERGY DRINK', 80], ['LARGE BREWED COFFEE', 200]] },
  { id: 'moonsize', prompt: 'SMALLEST → LARGEST MOON', promptAr: 'الأصغر ← الأكبر قمراً', unit: ' km across', items: [['PHOBOS', 22], ['ENCELADUS', 504], ['EUROPA', 3122], ['CALLISTO', 4821], ['GANYMEDE', 5268]] },
  { id: 'founded', prompt: 'OLDEST → NEWEST COUNTRY', promptAr: 'الأقدم ← الأحدث دولة', unit: ' AD', gapAbs: 8, items: [['SAN MARINO', 301], ['SWITZERLAND', 1291], ['USA', 1776], ['LEBANON', 1943], ['SOUTH SUDAN', 2011]] },
  { id: 'landmark', prompt: 'OLDEST → NEWEST LANDMARK', promptAr: 'الأقدم ← الأحدث معلماً', unit: ' AD', gapAbs: 8, items: [['COLOSSEUM', 80], ['HAGIA SOPHIA', 537], ['TAJ MAHAL', 1653], ['EIFFEL TOWER', 1889], ['BURJ KHALIFA', 2010]] },
  { id: 'discovery', prompt: 'EARLIEST → LATEST DISCOVERY', promptAr: 'الأقدم ← الأحدث اكتشافاً', unit: ' AD', gapAbs: 8, items: [['GRAVITY LAWS', 1687], ['OXYGEN', 1774], ['PENICILLIN', 1928], ['DNA STRUCTURE', 1953], ['BLACK HOLE IMAGE', 2019]] },
  { id: 'record', prompt: 'FASTEST → SLOWEST WORLD RECORD', promptAr: 'الأسرع ← الأبطأ رقماً', unit: ' sec', items: [['100 M', 9.58], ['400 M', 43.03], ['1500 M', 206], ['10000 M', 1571], ['MARATHON', 7235]] },
  { id: 'lake', prompt: 'SMALLEST → LARGEST LAKE', promptAr: 'الأصغر ← الأكبر بحيرة', unit: ' k km²', items: [['LAKE GENEVA', 0.58], ['LAKE ONTARIO', 19], ['LAKE BAIKAL', 31], ['LAKE SUPERIOR', 82], ['CASPIAN SEA', 371]] },
  { id: 'agefirst', prompt: 'EARLIEST → LATEST IN HISTORY', promptAr: 'الأقدم ← الأحدث تاريخياً', unit: ' k years ago', items: [['MOON LANDING', 0.06], ['ROMAN EMPIRE', 2], ['WRITING', 5], ['FARMING', 12], ['CAVE PAINTING', 36]] },
  { id: 'planetdens', prompt: 'LEAST → MOST DENSE PLANET', promptAr: 'الأقل ← الأكثر كثافة', unit: ' g/cm³', items: [['SATURN', 0.69], ['JUPITER', 1.33], ['NEPTUNE', 1.64], ['MARS', 3.93], ['EARTH', 5.51]] },
  { id: 'bodyorgan', prompt: 'LIGHTEST → HEAVIEST ORGAN', promptAr: 'الأخف ← الأثقل عضواً', unit: ' g', items: [['PITUITARY GLAND', 0.5], ['HEART', 300], ['BRAIN', 1350], ['LIVER', 1560], ['SKIN', 10000]] },
  { id: 'thermal', prompt: 'COLDEST → HOTTEST PLACE', promptAr: 'الأبرد ← الأسخن مكاناً', unit: ' °C', items: [['ANTARCTICA RECORD', -89], ['HOME FRIDGE', 4], ['ROOM', 21], ['DEATH VALLEY RECORD', 57], ['EARTH’S CORE', 5200]] },
].map(pool);
