/**
 * Labyrinth campaign — one floor per room key. RoomHost loads these via buildCampaignMaze.
 * Act 1: floor1 → floor2 → floor3 → boss1 → floor4 (chapter 2 start).
 */
export const CAMPAIGN_FLOORS = {
  floor1: {
    mapSize: 17,
    openChance: 0.52,
    wallHex: '#7e9bd0',
    floorHex: '#cdc6b6',
    labelEn: 'Floor 1 — Outer Labyrinth',
    labelAr: 'الطابق 1 — المتاهة الخارجية',
    soldier: {
      id: 'scout-aria',
      name: 'Scout Aria',
      nameAr: 'كشافة آريا',
      puzzleKey: 'takuzu',
      power: 8,
      color: '#5fa9d8',
      accessory: 'cap',
      scale: 0.95,
    },
    nextRoom: 'floor2',
  },
  floor2: {
    mapSize: 21,
    openChance: 0.42,
    wallHex: '#6a88c8',
    floorHex: '#c8c0b0',
    labelEn: 'Floor 2 — Inner Paths',
    labelAr: 'الطابق 2 — المسارات الداخلية',
    soldier: {
      id: 'knight-bram',
      name: 'Knight Bram',
      nameAr: 'الفارس برام',
      puzzleKey: 'kenken',
      power: 10,
      color: '#8cc06a',
      accessory: 'helmet',
      scale: 1.05,
      girth: 1.08,
    },
    nextRoom: 'floor3',
  },
  floor3: {
    mapSize: 25,
    openChance: 0.35,
    wallHex: '#5a78b8',
    floorHex: '#bfb8a8',
    labelEn: 'Floor 3 — Deep Maze',
    labelAr: 'الطابق 3 — المتاهة العميقة',
    soldier: {
      id: 'captain-lyn',
      name: 'Captain Lyn',
      nameAr: 'القائدة لين',
      puzzleKey: 'blockburst',
      power: 12,
      color: '#e6bd55',
      accessory: 'topknot',
      scale: 1.12,
      girth: 1.1,
    },
    nextRoom: 'boss1',
  },
  boss1: {
    mapSize: 15,
    openChance: 0.88,
    wallHex: '#4a5898',
    floorHex: '#b0a898',
    labelEn: 'Boss — The Gatekeeper',
    labelAr: 'الزعيم — حارس البوابة',
    isBoss: true,
    soldier: {
      id: 'boss-gatekeeper',
      name: 'The Gatekeeper',
      nameAr: 'حارس البوابة',
      puzzleKey: 'bridges',
      power: 14,
      color: '#b696d4',
      accessory: 'horns',
      scale: 1.35,
      girth: 1.15,
    },
    nextRoom: 'floor4',
  },
  floor4: {
    mapSize: 19,
    openChance: 0.48,
    wallHex: '#9a78c0',
    floorHex: '#d0c4b8',
    labelEn: 'Chapter 2 — Floor 1',
    labelAr: 'الفصل 2 — الطابق 1',
    soldier: {
      id: 'mage-sole',
      name: 'Mage Sole',
      nameAr: 'الساحرة سول',
      puzzleKey: 'hitori',
      power: 9,
      color: '#e07aaa',
      accessory: 'wizard',
      scale: 1.08,
    },
    nextRoom: 'floor4',
  },
};

export const CAMPAIGN_ROOM_KEYS = Object.keys(CAMPAIGN_FLOORS);
