import { assetUrl } from '../../lib/assetUrl';

/*
 * The Kawnera shelf — book metadata only.
 *
 * Split out of KawneraExperience so Home can read the titles and chapter lists
 * WITHOUT pulling in the Kawnera chunk. Home draws a body per learned chapter
 * and needs their names; importing the experience for that would drag three.js,
 * the 600KB chapter bank and the authored content into the entry bundle and
 * undo the lazy split the gateway exists for.
 */
export const KAWNERA_BOOKS = [
  {
    id: 'enigma',
    code: 'ER',
    title: 'The Enigma of Reason',
    author: 'Hugo Mercier & Dan Sperber',
    pages: '405',
    color: '#ffcf55',
    image: assetUrl('Assets/kawnera/covers/enigma-of-reason.webp'),
    desc: 'Why did reason evolve, why is it biased, and why does it often work better between people than inside one isolated mind?',
    chapters: [
      'Reason on Trial',
      'Psychologists’ Travails',
      'From Unconscious Inferences to Intuitions',
      'Modularity',
      'Cognitive Opportunism',
      'Metarepresentations',
      'How We Use Reasons',
      'Could Reason Be a Module?',
      'Reasoning: Intuition and Reflection',
      'Reason: What Is It For?',
      'Why Is Reasoning Biased?',
      'Quality Control: How We Evaluate Arguments',
      'The Dark Side of Reason',
      'A Reason for Everything',
      'The Bright Side of Reason',
      'Is Human Reason Universal?',
      'Reasoning about Moral and Political Topics',
      'Solitary Geniuses?',
    ],
  },
  {
    id: 'social',
    code: 'SC',
    title: 'Social Cognition',
    author: 'Susan T. Fiske & Shelley E. Taylor',
    pages: '1,020',
    color: '#6fd3c7',
    image: assetUrl('Assets/kawnera/covers/social-cognition.webp'),
    desc: 'A broad map of how people perceive themselves and others, from attention and memory to attitudes, stereotypes, affect, and culture.',
    chapters: [
      'Introduction',
      'Dual Modes in Social Cognition',
      'Attention and Encoding',
      'Representation in Memory',
      'Self in Social Cognition',
      'Attribution Processes',
      'Heuristics and Shortcuts',
      'Accuracy and Efficiency in Social Inference',
      'Cognitive Structures of Attitudes',
      'Cognitive Processing of Attitudes',
      'Stereotyping: Cognition and Bias',
      'Prejudice: Cognitive and Affective Biases',
      'From Social Cognition to Affect',
      'From Affect to Social Cognition',
      'Behavior and Cognition',
    ],
  },
  {
    id: 'mindreading',
    code: 'MR',
    title: 'Mindreading and Social Cognition',
    author: 'Jane Suilin Lavelle',
    pages: '88',
    color: '#9994ef',
    image: assetUrl('Assets/kawnera/covers/mindreading.webp'),
    desc: 'A concise philosophical challenge to the idea that one universal mindreading mechanism underlies most social interaction.',
    chapters: [
      'Introduction',
      'A Brief History of Mindreading',
      'The New Pluralism',
      'Mindreading in Infancy',
      'Mindreading across Cultures',
      'Power Differentials and Mindreading',
      'Conclusions',
    ],
  },
  {
    id: 'thinking',
    code: 'TH',
    title: 'Oxford Handbook of Thinking and Reasoning',
    author: 'Keith J. Holyoak & Robert G. Morrison',
    pages: '865',
    color: '#f08f82',
    image: assetUrl('Assets/kawnera/covers/thinking-reasoning.webp'),
    desc: 'A research handbook spanning inference, decisions, problem solving, creativity, development, culture, and thinking in practice.',
    chapters: [
      'Thinking and Reasoning: A Reader’s Guide',
      'Normative Systems: Logic, Probability, and Rational Choice',
      'Bayesian Inference',
      'Knowledge Representation',
      'Computational Models of Higher Cognition',
      'Neurocognitive Methods in Higher Cognition',
      'Mental Function as Genetic Expression',
      'Dual-Process Theories of Deductive Reasoning',
      'Inference in Mental Models',
      'Similarity',
      'Concepts and Categories',
      'Causal Learning',
      'Analogy and Relational Reasoning',
      'Explanation and Abductive Inference',
      'Rational Argument',
      'Decision Making',
      'Judgmental Heuristics',
      'Cognitive Hierarchies and Emotions in Behavioral Game Theory',
      'Moral Judgment',
      'Motivated Thinking',
      'Problem Solving',
      'Rationality and Intelligence',
      'Cognition and the Creation of Ideas',
      'Insight',
      'Genius',
      'Development of Thinking in Children',
      'The Human Enigma',
      'Language and Thought',
      'Thinking in Societies and Cultures',
      'Development of Quantitative Thinking',
      'Visuospatial Thinking',
      'Gesture in Thought',
      'Impact of Aging on Thinking',
      'Thought Disorder in Schizophrenia',
      'Scientific Thinking and Reasoning',
      'Legal Reasoning',
      'Medical Reasoning and Thinking',
      'Thinking in Business',
      'Musical Thought',
      'Learning to Think: Knowledge Transfer',
    ],
  },
  {
    id: 'emotion',
    code: 'CE',
    title: 'Cognition and Emotion',
    author: 'Mick Power & Tim Dalgleish',
    pages: '473',
    color: '#a8d663',
    image: assetUrl('Assets/kawnera/covers/cognition-emotion.webp'),
    desc: 'An integrated account of normal emotion and emotional disorder, organized around appraisal, representation, and the SPAARS model.',
    chapters: [
      'Introduction',
      'The Cognitive Philosophy of Emotion',
      'Cognitive Theories of Emotion',
      'Cognitive Theories of Emotional Disorder',
      'The SPAARS Approach',
      'Fear',
      'Sadness',
      'Anger',
      'Disgust',
      'Happiness',
      'Overview and Conclusions',
    ],
  },
  {
    id: 'remediation',
    code: 'CR',
    title: 'Cognitive Remediation for Psychological Disorders',
    author: 'Medalia, Herlands, Saperstein & Revheim',
    pages: '241',
    color: '#e6a15c',
    image: assetUrl('Assets/kawnera/covers/cognitive-remediation.webp'),
    desc: 'A therapist-facing, practical guide to designing and delivering cognitive remediation programs that connect training to daily goals.',
    chapters: [
      'Introductory Information for Therapists',
      'Treatment Principles',
      'Setting Up a Cognitive Remediation Program',
      'Choosing Computerized Cognitive Exercises',
      'Intake and Assessment',
      'Treatment Planning',
      'Treating Specific Cognitive Deficits',
      'Phases of Treatment',
      'Bridging Groups',
      'Difficult Clinical Situations',
      'Program Evaluation',
    ],
  },
  {
    id: 'outcomes',
    code: 'FO',
    title: 'Cognitive Remediation to Improve Functional Outcomes',
    author: 'Alice Medalia & Christopher R. Bowie',
    pages: '233',
    color: '#e7c855',
    image: assetUrl('Assets/kawnera/covers/functional-outcomes.webp'),
    desc: 'How cognitive remediation can transfer beyond training tasks into functional improvement, engagement, metacognition, and social cognition.',
    chapters: [
      'Cognitive Remediation: An Overview',
      'Assessment and Functional Goals',
      'Treatment Planning',
      'Bridging Groups',
      'A Metacognitive Approach',
      'Implementation and Dissemination',
      'Cognitive Distortions and Engagement',
      'Choosing Computerized Exercises',
      'Compensatory Approaches',
      'Integrating Social Cognitive Training',
    ],
  },
  {
    id: 'problems',
    code: 'PS',
    title: 'Problem Solving',
    author: 'S. Ian Robertson',
    pages: '287',
    color: '#71b9d0',
    image: assetUrl('Assets/kawnera/covers/problem-solving.webp'),
    desc: 'A clear progression from problem representation and transfer to expertise, insight, creativity, and the neuroscience of solving.',
    chapters: [
      'What Is Involved in Problem Solving?',
      'Problem Representation',
      'Transfer',
      'Worked Examples and Instructional Design',
      'Developing Skill',
      'Developing Expertise',
      'Insight',
      'Creative Problem Solving',
      'The Neuroscience of Problem Solving',
      'Conclusion',
    ],
  },
  {
    id: 'assessment',
    code: 'IA',
    title: 'Contemporary Intellectual Assessment',
    author: 'Dawn P. Flanagan & Erin M. McDonough',
    pages: '1,154',
    color: '#d49ac6',
    image: assetUrl('Assets/kawnera/covers/intellectual-assessment.webp'),
    desc: 'A comprehensive guide to theories, instruments, interpretation, fairness, intervention, and emerging issues in intellectual assessment.',
    chapters: [
      'History of Intelligence Assessment',
      'History of Intelligence Test Interpretation',
      'Cattell-Horn-Carroll Theory',
      'Multiple-Intelligences Theory',
      'Triarchic Theory of Successful Intelligence',
      'PASS Theory of Neurocognitive Processes',
      'Parieto-Frontal Integration Theory',
      'Intelligence as Process, Personality, Interests, and Knowledge',
      'Wechsler Preschool, Child, and Achievement Scales',
      'Woodcock-Johnson IV Early Cognitive and Academic Development',
      'WISC-V Integrated',
      'Kaufman Assessment Battery for Children',
      'Differential Ability Scales',
      'Woodcock-Johnson IV Batteries',
      'Cognitive Assessment System',
      'WAIS-IV and WMS-IV',
      'Wechsler Nonverbal Scale',
      'Reynolds Intellectual Assessment Scales',
      'NEPSY-II',
      'Universal Nonverbal Intelligence Test',
      'Identifying Giftedness',
      'Identifying Specific Learning Disabilities',
      'Intellectual Disability Assessment',
      'Sensory, Physical Disability, and Brain Injury',
      'Culturally and Linguistically Diverse Populations',
      'Cognitive Hypothesis Testing',
      'Cross-Battery Assessment',
      'Abilities and Academic Interventions',
      'KTEA-3 and WISC-V Integration',
      'Joint Test Standards and Validity',
      'Confirmatory Factor Analysis',
      'Functional CHC Nomenclature',
      'Neuropsychological Constructs in Intelligence Tests',
      'Reading Disorders and Neuropsychological Tests',
      'Orthographic Mapping and SLD Diagnosis',
      'Assessment of Executive Functions',
      'DSM-5 Specific Learning Disorder',
      'Neuropsychological Services in Schools',
      'Assessment in Three-Tiered School Systems',
    ],
  },
];
